from __future__ import annotations

FIXTURE_RECIPES: list[dict[str, object]] = [
    {
        "id": "11111111-1111-1111-1111-111111111111",
        "title": "Scrambled Eggs",
        "prep_minutes": 10,
        "image_url": "https://img.spoonacular.com/recipes/641803-556x370.jpg",
        "source_url": "https://www.simplyrecipes.com/recipes/perfect_scrambled_eggs/",
        "summary": "Soft scrambled eggs cooked gently with butter for a quick, comforting breakfast. It is simple, protein-rich, and ideal for using up fresh eggs fast.",
        "instructions": [
            {"number": 1, "step": "Crack the eggs into a bowl and whisk until smooth."},
            {"number": 2, "step": "Melt the butter in a nonstick skillet over low heat."},
            {"number": 3, "step": "Pour in the eggs and stir slowly with a spatula as curds begin to form."},
            {"number": 4, "step": "Cook until softly set and serve immediately."},
        ],
        "cuisines": ["American"],
        "servings": 1,
        "nutrition": {"calories": "220 kcal", "protein": "13g", "fat": "17g", "carbs": "2g"},
        "dietary_tags": ["gluten-free", "high-protein"],
        "ingredients": [
            {"canonical_name": "eggs", "quantity": 2.0, "unit": "unit"},
            {"canonical_name": "butter", "quantity": 1.0, "unit": "tbsp"},
        ],
    },
    {
        "id": "22222222-2222-2222-2222-222222222222",
        "title": "Chicken Stir Fry",
        "prep_minutes": 20,
        "image_url": "https://img.spoonacular.com/recipes/716426-556x370.jpg",
        "source_url": "https://www.recipetineats.com/chicken-stir-fry/",
        "summary": "Tender chicken and crisp vegetables are quickly stir-fried in a savory pan sauce. This weeknight dinner comes together fast and works well with produce on hand.",
        "instructions": [
            {"number": 1, "step": "Slice the chicken into thin strips and season lightly."},
            {"number": 2, "step": "Cook the chicken in a hot skillet until browned and nearly cooked through."},
            {"number": 3, "step": "Add the carrots and spinach and stir-fry until just tender."},
            {"number": 4, "step": "Pour in the sauce and toss until everything is glossy and cooked through."},
        ],
        "cuisines": ["Asian"],
        "servings": 3,
        "nutrition": {"calories": "360 kcal", "protein": "34g", "fat": "14g", "carbs": "18g"},
        "dietary_tags": ["dairy-free", "high-protein"],
        "ingredients": [
            {"canonical_name": "chicken", "quantity": 500.0, "unit": "g"},
            {"canonical_name": "carrots", "quantity": 2.0, "unit": "piece"},
            {"canonical_name": "spinach", "quantity": 100.0, "unit": "g"},
        ],
    },
    {
        "id": "33333333-3333-3333-3333-333333333333",
        "title": "Pasta Bolognese",
        "prep_minutes": 40,
        "image_url": "https://img.spoonacular.com/recipes/715497-556x370.jpg",
        "source_url": "https://www.bbcgoodfood.com/recipes/best-spaghetti-bolognese-recipe",
        "summary": "A hearty tomato and beef sauce tossed with pasta for a classic family-style dinner. It is rich, filling, and great for pantry staples plus fresh tomatoes.",
        "instructions": [
            {"number": 1, "step": "Cook the pasta in salted boiling water until al dente."},
            {"number": 2, "step": "Brown the beef in a skillet, breaking it into small pieces."},
            {"number": 3, "step": "Add chopped tomatoes and simmer until the sauce thickens."},
            {"number": 4, "step": "Toss the drained pasta with the sauce and serve warm."},
        ],
        "cuisines": ["Italian"],
        "servings": 4,
        "nutrition": {"calories": "540 kcal", "protein": "28g", "fat": "18g", "carbs": "61g"},
        "dietary_tags": ["high-protein"],
        "ingredients": [
            {"canonical_name": "pasta", "quantity": 200.0, "unit": "g"},
            {"canonical_name": "beef", "quantity": 300.0, "unit": "g"},
            {"canonical_name": "tomatoes", "quantity": 3.0, "unit": "piece"},
        ],
    },
    {
        "id": "44444444-4444-4444-4444-444444444444",
        "title": "Banana Smoothie",
        "prep_minutes": 5,
        "image_url": "https://img.spoonacular.com/recipes/636589-556x370.jpg",
        "source_url": "https://www.loveandlemons.com/banana-smoothie/",
        "summary": "Ripe bananas and milk are blended into a creamy smoothie with naturally sweet flavor. It is an easy breakfast or snack for using bananas before they overripen.",
        "instructions": [
            {"number": 1, "step": "Peel the bananas and break them into chunks."},
            {"number": 2, "step": "Add the bananas and milk to a blender."},
            {"number": 3, "step": "Blend until smooth and frothy."},
            {"number": 4, "step": "Pour into a glass and serve cold."},
        ],
        "cuisines": ["American"],
        "servings": 2,
        "nutrition": {"calories": "210 kcal", "protein": "7g", "fat": "4g", "carbs": "39g"},
        "dietary_tags": ["vegetarian", "kid-friendly"],
        "ingredients": [
            {"canonical_name": "bananas", "quantity": 2.0, "unit": "piece"},
            {"canonical_name": "milk", "quantity": 200.0, "unit": "ml"},
        ],
    },
    {
        "id": "55555555-5555-5555-5555-555555555555",
        "title": "French Toast",
        "prep_minutes": 15,
        "image_url": "https://img.spoonacular.com/recipes/640941-556x370.jpg",
        "source_url": "https://www.allrecipes.com/recipe/7016/french-toast-i/",
        "summary": "Bread slices are dipped in a simple egg custard and pan-fried until golden. This breakfast favorite turns staple ingredients into a warm, satisfying meal.",
        "instructions": [
            {"number": 1, "step": "Whisk the eggs and milk together in a shallow bowl."},
            {"number": 2, "step": "Dip each bread slice in the mixture until coated."},
            {"number": 3, "step": "Melt the butter in a skillet over medium heat."},
            {"number": 4, "step": "Cook the bread on both sides until golden and set."},
        ],
        "cuisines": ["French", "American"],
        "servings": 2,
        "nutrition": {"calories": "330 kcal", "protein": "12g", "fat": "14g", "carbs": "38g"},
        "dietary_tags": ["vegetarian"],
        "ingredients": [
            {"canonical_name": "bread", "quantity": 2.0, "unit": "slice"},
            {"canonical_name": "eggs", "quantity": 2.0, "unit": "unit"},
            {"canonical_name": "milk", "quantity": 50.0, "unit": "ml"},
            {"canonical_name": "butter", "quantity": 1.0, "unit": "tbsp"},
        ],
    },
    {
        "id": "66666666-6666-6666-6666-666666666666",
        "title": "Apple Salad",
        "prep_minutes": 10,
        "image_url": "https://img.spoonacular.com/recipes/632660-556x370.jpg",
        "source_url": "https://www.eatingwell.com/recipe/250222/apple-salad/",
        "summary": "Fresh apples and crisp lettuce make a light salad with bright, clean flavors. It is a refreshing no-cook option for produce that needs to be used quickly.",
        "instructions": [
            {"number": 1, "step": "Wash and dry the lettuce, then tear it into bite-size pieces."},
            {"number": 2, "step": "Core and thinly slice the apples."},
            {"number": 3, "step": "Combine the apples and lettuce in a large bowl."},
            {"number": 4, "step": "Toss gently with dressing just before serving."},
        ],
        "cuisines": ["American"],
        "servings": 2,
        "nutrition": {"calories": "140 kcal", "protein": "2g", "fat": "5g", "carbs": "24g"},
        "dietary_tags": ["vegan", "vegetarian", "gluten-free", "dairy-free"],
        "ingredients": [
            {"canonical_name": "apples", "quantity": 2.0, "unit": "piece"},
            {"canonical_name": "lettuce", "quantity": 1.0, "unit": "head"},
        ],
    },
    {
        "id": "77777777-7777-7777-7777-777777777777",
        "title": "Beef Stew",
        "prep_minutes": 90,
        "image_url": "https://img.spoonacular.com/recipes/633508-556x370.jpg",
        "source_url": "https://www.foodnetwork.com/recipes/food-network-kitchen/beef-stew-recipe-1973438",
        "summary": "Chunks of beef are slowly simmered with root vegetables until tender and deeply flavorful. The long cook creates a cozy meal that is perfect for colder days.",
        "instructions": [
            {"number": 1, "step": "Brown the beef in a heavy pot until deeply caramelized."},
            {"number": 2, "step": "Add chopped onions and cook until softened."},
            {"number": 3, "step": "Stir in the carrots and potatoes with enough liquid to cover."},
            {"number": 4, "step": "Simmer gently until the beef is fork-tender and the broth thickens."},
            {"number": 5, "step": "Taste, adjust seasoning, and serve hot."},
        ],
        "cuisines": ["American", "Irish"],
        "servings": 4,
        "nutrition": {"calories": "480 kcal", "protein": "35g", "fat": "22g", "carbs": "28g"},
        "dietary_tags": ["dairy-free", "gluten-free", "high-protein"],
        "ingredients": [
            {"canonical_name": "beef", "quantity": 400.0, "unit": "g"},
            {"canonical_name": "potatoes", "quantity": 3.0, "unit": "piece"},
            {"canonical_name": "carrots", "quantity": 2.0, "unit": "piece"},
            {"canonical_name": "onions", "quantity": 1.0, "unit": "piece"},
        ],
    },
    {
        "id": "88888888-8888-8888-8888-888888888888",
        "title": "Vegetable Rice",
        "prep_minutes": 30,
        "image_url": "https://img.spoonacular.com/recipes/661340-556x370.jpg",
        "source_url": "https://www.indianhealthyrecipes.com/vegetable-rice/",
        "summary": "Rice is cooked with sweet carrots and onions for a simple, versatile side or main. It is budget-friendly and easy to adapt with extra vegetables.",
        "instructions": [
            {"number": 1, "step": "Rinse the rice until the water runs mostly clear."},
            {"number": 2, "step": "Saute the onions and carrots in a pot until fragrant."},
            {"number": 3, "step": "Add the rice and stir briefly to coat."},
            {"number": 4, "step": "Pour in water, cover, and cook until the rice is tender."},
            {"number": 5, "step": "Fluff with a fork before serving."},
        ],
        "cuisines": ["Asian"],
        "servings": 3,
        "nutrition": {"calories": "310 kcal", "protein": "6g", "fat": "6g", "carbs": "57g"},
        "dietary_tags": ["vegetarian", "dairy-free"],
        "ingredients": [
            {"canonical_name": "rice", "quantity": 200.0, "unit": "g"},
            {"canonical_name": "carrots", "quantity": 1.0, "unit": "piece"},
            {"canonical_name": "onions", "quantity": 1.0, "unit": "piece"},
        ],
    },
    {
        "id": "99999999-9999-9999-9999-999999999999",
        "title": "Greek Yogurt Bowl",
        "prep_minutes": 5,
        "image_url": "https://img.spoonacular.com/recipes/648279-556x370.jpg",
        "source_url": "https://www.delish.com/cooking/recipe-ideas/a19665918/yogurt-breakfast-bowl-recipe/",
        "summary": "Creamy Greek yogurt topped with banana makes a fast, balanced breakfast bowl. It is cool, lightly sweet, and easy to assemble in minutes.",
        "instructions": [
            {"number": 1, "step": "Spoon the yogurt into a serving bowl."},
            {"number": 2, "step": "Slice the banana into coins."},
            {"number": 3, "step": "Top the yogurt with the banana and serve immediately."},
        ],
        "cuisines": ["Mediterranean"],
        "servings": 1,
        "nutrition": {"calories": "250 kcal", "protein": "18g", "fat": "6g", "carbs": "28g"},
        "dietary_tags": ["vegetarian", "gluten-free", "high-protein"],
        "ingredients": [
            {"canonical_name": "yogurt", "quantity": 200.0, "unit": "g"},
            {"canonical_name": "bananas", "quantity": 1.0, "unit": "piece"},
        ],
    },
    {
        "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        "title": "Tomato Soup",
        "prep_minutes": 25,
        "image_url": "https://img.spoonacular.com/recipes/716429-556x370.jpg",
        "source_url": "https://www.loveandlemons.com/tomato-soup-recipe/",
        "summary": "A smooth tomato soup with sweet onion flavor and a bright, comforting finish. It is a simple plant-based recipe that makes good use of ripe tomatoes.",
        "instructions": [
            {"number": 1, "step": "Saute the onions in a pot until soft and translucent."},
            {"number": 2, "step": "Add chopped tomatoes and cook until they begin to break down."},
            {"number": 3, "step": "Simmer with stock until the vegetables are tender."},
            {"number": 4, "step": "Blend until smooth and heat through before serving."},
        ],
        "cuisines": ["Mediterranean"],
        "servings": 3,
        "nutrition": {"calories": "170 kcal", "protein": "4g", "fat": "6g", "carbs": "27g"},
        "dietary_tags": ["vegan", "vegetarian", "dairy-free"],
        "ingredients": [
            {"canonical_name": "tomatoes", "quantity": 5.0, "unit": "piece"},
            {"canonical_name": "onions", "quantity": 1.0, "unit": "piece"},
        ],
    },
    {
        "id": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        "title": "Oatmeal Bowl",
        "prep_minutes": 8,
        "image_url": "https://img.spoonacular.com/recipes/652423-556x370.jpg",
        "source_url": "https://www.acouplecooks.com/oatmeal-recipe/",
        "summary": "Warm oats simmered in milk and finished with sliced banana create a cozy breakfast bowl. It is filling, pantry-friendly, and easy to customize.",
        "instructions": [
            {"number": 1, "step": "Combine the oats and milk in a small saucepan."},
            {"number": 2, "step": "Cook over medium heat, stirring occasionally, until creamy."},
            {"number": 3, "step": "Transfer to a bowl and top with sliced banana."},
        ],
        "cuisines": ["American"],
        "servings": 1,
        "nutrition": {"calories": "290 kcal", "protein": "10g", "fat": "7g", "carbs": "48g"},
        "dietary_tags": ["vegetarian", "high-fiber"],
        "ingredients": [
            {"canonical_name": "oats", "quantity": 80.0, "unit": "g"},
            {"canonical_name": "milk", "quantity": 200.0, "unit": "ml"},
            {"canonical_name": "bananas", "quantity": 1.0, "unit": "piece"},
        ],
    },
]
