"""initial schema

Revision ID: 9c891418bc24
Revises: 
Create Date: 2026-04-25 09:43:09.073454+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c891418bc24'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_inference_log',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('api_points_used', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('items_returned', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_inference_log_created_at'), 'ai_inference_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_inference_log_provider'), 'ai_inference_log', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_inference_log_user_id'), 'ai_inference_log', ['user_id'], unique=False)
    op.create_table('api_request_log',
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_log_created_at'), 'api_request_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_log_path'), 'api_request_log', ['path'], unique=False)
    op.create_index(op.f('ix_api_request_log_user_id'), 'api_request_log', ['user_id'], unique=False)
    op.create_table('canonical_ingredients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_ingredients_name'), 'canonical_ingredients', ['name'], unique=True)
    op.create_table('households',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_invite_code'), 'households', ['invite_code'], unique=True)
    op.create_table('recipes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('cuisines', sa.JSON(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('dietary_tags', sa.JSON(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analytics_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('household_members',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='householdrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_members_user_id'), 'household_members', ['user_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=False),
    sa.Column('estimated_expiry_date', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'used', 'discarded', 'frozen', name='inventorystatus'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'barcode', 'photo', name='inventorysource'), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['canonical_ingredients.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_canonical_ingredient_id'), 'inventory_items', ['canonical_ingredient_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_household_id'), 'inventory_items', ['household_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_user_id'), 'inventory_items', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_household_id'), 'meal_plans', ['household_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expiry_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('product_barcodes',
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('canonical_ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['canonical_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcodes_barcode'), 'product_barcodes', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_barcodes_canonical_ingredient_id'), 'product_barcodes', ['canonical_ingredient_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['canonical_ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_canonical_ingredient_id'), 'recipe_ingredients', ['canonical_ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recommendation_sessions',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('recipes_shown', sa.JSON(), nullable=False),
    sa.Column('recipe_selected_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_sessions_household_id'), 'recommendation_sessions', ['household_id'], unique=False)
    op.create_table('shelf_life_rules',
    sa.Column('canonical_ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['canonical_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_life_rules_canonical_ingredient_id'), 'shelf_life_rules', ['canonical_ingredient_id'], unique=False)
    op.create_table('inventory_events',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('new_state', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_events_household_id'), 'inventory_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_inventory_events_item_id'), 'inventory_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_events_user_id'), 'inventory_events', ['user_id'], unique=False)
    op.create_table('meal_plan_days',
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_days_meal_plan_id'), 'meal_plan_days', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_days_recipe_id'), 'meal_plan_days', ['recipe_id'], unique=False)
    op.create_table('reserved_ingredients',
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('meal_plan_day_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_reserved', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_day_id'], ['meal_plan_days.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserved_ingredients_inventory_item_id'), 'reserved_ingredients', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_reserved_ingredients_meal_plan_day_id'), 'reserved_ingredients', ['meal_plan_day_id'], unique=False)
    op.create_index(op.f('ix_reserved_ingredients_meal_plan_id'), 'reserved_ingredients', ['meal_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserved_ingredients_meal_plan_id'), table_name='reserved_ingredients')
    op.drop_index(op.f('ix_reserved_ingredients_meal_plan_day_id'), table_name='reserved_ingredients')
    op.drop_index(op.f('ix_reserved_ingredients_inventory_item_id'), table_name='reserved_ingredients')
    op.drop_table('reserved_ingredients')
    op.drop_index(op.f('ix_meal_plan_days_recipe_id'), table_name='meal_plan_days')
    op.drop_index(op.f('ix_meal_plan_days_meal_plan_id'), table_name='meal_plan_days')
    op.drop_table('meal_plan_days')
    op.drop_index(op.f('ix_inventory_events_user_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_item_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_household_id'), table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_index(op.f('ix_shelf_life_rules_canonical_ingredient_id'), table_name='shelf_life_rules')
    op.drop_table('shelf_life_rules')
    op.drop_index(op.f('ix_recommendation_sessions_household_id'), table_name='recommendation_sessions')
    op.drop_table('recommendation_sessions')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_canonical_ingredient_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_product_barcodes_canonical_ingredient_id'), table_name='product_barcodes')
    op.drop_index(op.f('ix_product_barcodes_barcode'), table_name='product_barcodes')
    op.drop_table('product_barcodes')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_household_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_inventory_items_user_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_household_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_canonical_ingredient_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_household_members_user_id'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_households_invite_code'), table_name='households')
    op.drop_table('households')
    op.drop_index(op.f('ix_canonical_ingredients_name'), table_name='canonical_ingredients')
    op.drop_table('canonical_ingredients')
    op.drop_index(op.f('ix_api_request_log_user_id'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_path'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_created_at'), table_name='api_request_log')
    op.drop_table('api_request_log')
    op.drop_index(op.f('ix_ai_inference_log_user_id'), table_name='ai_inference_log')
    op.drop_index(op.f('ix_ai_inference_log_provider'), table_name='ai_inference_log')
    op.drop_index(op.f('ix_ai_inference_log_created_at'), table_name='ai_inference_log')
    op.drop_table('ai_inference_log')
    # ### end Alembic commands ###

    # PostgreSQL ENUM types are not auto-dropped by Alembic when their owning
    # tables are dropped, so a subsequent `upgrade` would fail with
    # DuplicateObjectError. Drop them explicitly. Guarded so downgrade is a
    # no-op on dialects without ENUM support (e.g. SQLite).
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name in ('inventorysource', 'inventorystatus', 'householdrole'):
            op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
