"""add shopping_list_items table

Revision ID: b00b9c13cc2d
Revises: 9c891418bc24
Create Date: 2026-04-25 13:16:34.975852+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00b9c13cc2d'
down_revision: str | Sequence[str] | None = '9c891418bc24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table('shopping_list_items',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'idempotency_key', name='uq_shopping_list_items_household_idempotency')
    )
    op.create_index(op.f('ix_shopping_list_items_household_id'), 'shopping_list_items', ['household_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_recipe_id'), 'shopping_list_items', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_items_recipe_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_household_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    # ### end Alembic commands ###
